[package]
name = "custom-mpd-client"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
mpd = "0.1.0"
rand = "0.9.2"
ratatui = "0.29.0"
regex = "1.11.3"
serde = "1.0.227"
serde_json = "1.0.145"


